export const TYPEORM_HISTORY_OPTIONS = 'TYPEORM_HISTORY_OPTIONS';
export const TYPEORM_HISTORY_MAPPED_COLUMNS = 'TYPEORM_HISTORY_MAPPED_COLUMNS ';
export const TYPEORM_HISTORY_HISTORY_FOR = 'TYPEORM_HISTORY_HISTORY_FOR ';
export const TYPEORM_HISTORY_SNAPSHOT_COLUMN =
  'TYPEORM_HISTORY_SNAPSHOT_COLUMN ';
export const TYPEORM_HISTORY_ACTION_COLUMN = 'TYPEORM_HISTORY_ACTION_COLUMN ';
