name: ci-nestjs-typeorm-history

on:
  push:
    paths:
      - "packages/nestjs-typeorm-history/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/nestjs-typeorm-history/**"
    branches:
      - main

defaults:
  run:
    working-directory: packages/nestjs-typeorm-history

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: load cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: npm test
        run: npm test
      - name: Release
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx npm version 0.0.0-${GITHUB_SHA: -7} --git-tag-version=false
          npm publish --tag=next
